In [1]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [2]:
din = inputs.shape[1]
dout = 2

In [4]:
Wq = torch.nn.Parameter(torch.rand(din, dout), requires_grad=False)
Wk = torch.nn.Parameter(torch.rand(din, dout), requires_grad=False)
Wv = torch.nn.Parameter(torch.rand(din, dout), requires_grad=False)


In [5]:
Key = inputs @ Wk
Query = inputs @ Wk
Value = inputs @ Wv

In [8]:
attention_score = Query @ Key.T
attention_weight = torch.softmax(attention_score / (Key.shape[-1] ** 0.5), dim = -1)


In [11]:
context_vector = attention_weight @ inputs
print(context_vector)

tensor([[0.4490, 0.6776, 0.5897],
        [0.4620, 0.7231, 0.6095],
        [0.4614, 0.7213, 0.6088],
        [0.4427, 0.6672, 0.5810],
        [0.4409, 0.6475, 0.5724],
        [0.4490, 0.6921, 0.5934]])


In [19]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
  def __init__(self, din, dout):
    super().__init__()
    self.wq = nn.Parameter(torch.rand(din, dout), requires_grad=False)
    self.wk = nn.Parameter(torch.rand(din, dout), requires_grad=False)
    self.wv = nn.Parameter(torch.rand(din, dout), requires_grad=False)
  def forward(self, x):
    query = x @ self.wq
    key = x @ self.wk
    value = x @ self.wv
    attention_scores = query @ key.T
    attention_weights = torch.softmax(attention_scores / (key.shape[-1] ** 0.5) , dim = -1)
    context_vector = attention_weights @ value
    return context_vector


In [20]:
torch.manual_seed(123)
att = SelfAttention_v1(din, dout)
print(att(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]])


In [26]:
class SelfAttention_v2(nn.Module):
  def __init__(self, din, dout, qkv_bias=False):
    super().__init__()
    self.Wq = nn.Linear(din, dout, bias = qkv_bias)
    self.Wk = nn.Linear(din, dout, bias = qkv_bias)
    self.Wv = nn.Linear(din, dout, bias = qkv_bias)
  def forward(self, x):
    query = x @ Wq
    key = x @ Wk
    value = x @ Wv
    attention_scores = query @ key.T
    attention_weights = torch.softmax(attention_scores / (key.shape[-1] ** 0.5) , dim = -1)
    context_vector = attention_weights @ value
    return context_vector


In [27]:
att = SelfAttention_v2(din, dout)
print(att(inputs))

tensor([[0.7923, 0.8296],
        [0.8187, 0.8530],
        [0.8183, 0.8527],
        [0.7944, 0.8306],
        [0.7953, 0.8326],
        [0.8004, 0.8356]])
